# Site settings
title: ANDRASKINDLER
email: andraskindler@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Posts about development, mostly focused Android.

baseurl: "" # the subpath of your site, e.g. /blog/
permalink: '/blog/:year/:title/'
paginate_path: '/blog/page:num/'
paginate: 8
relative_permalinks: false
excerpt_separator: "<!-- more -->"

url: "http://andraskindler.com" # the base hostname & protocol for your site
twitter_username: andraskindler
github_username: andraskindler
name: Andras Kindler

# Build settings
markdown: kramdown
