# Site settings
title: ANDRASKINDLER
email: andraskindler@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Posts about development, mostly focused on Android.

baseurl: ""
permalink: '/blog/:year/:title/'
paginate_path: '/blog/page:num/'
paginate: 8
relative_permalinks: false
excerpt_separator: "<!-- more -->"

url: "http://andraskindler.com"
twitter_username: andraskindler
github_username: andraskindler
name: Andras Kindler

# Build settings
markdown: kramdown

gems:
  - jekyll-redirect-from
  - jekyll-sitemap