# Site settings
title: RANGKEN
email: rangken@gmail.com
description: > # rangken programming blog "baseurl:"

baseurl: ""
permalink: '/blog/:year/:title/'
paginate_path: '/blog/page:num/'
paginate: 8
relative_permalinks: false
excerpt_separator: "<!-- more -->"

url: "http://rangken.github.com"
twitter_username: rangken87
github_username: rangken
name: Jaeyoung Kim

# Build settings
markdown: kramdown

gems: ["jekyll-redirect-from", "emoji_for_jekyll", "jekyll-sitemap"]
